name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola-component-db-writer-hive
  AWS_ACCESS_KEY_ID: "AKIATDSWT5244OKFBS7I"
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_USER: "keboolabot"
  KBC_DEVELOPERPORTAL_VENDOR: "keboola"
  KBC_DEVELOPERPORTAL_APP: "keboola.ex-db-hive"
  KBC_DEVELOPERPORTAL_USERNAME: "keboola+wr_db_hive_gha"
  KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hive_version: ['2.3.6', '1.1.0', '1.2.0', '2.0.0', '2.1.0', '2.2.0', '2.3.0']
        include:
          - hive_version: '2.3.6'
            run_push: 'true'
            run_deploy: 'true'
    env:
      HIVE_VERSION: ${{ matrix.hive_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Print Docker version
        run: |
          docker -v
          docker compose version
      - name: Build image
        run: |
          docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
          source ./set_env_vars.sh
          docker build --build-arg AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY -t $APP_IMAGE .
      - name: Run tests
        run: |
          source ./set_env_vars.sh
          docker network create hivedb
          docker compose run --rm wait
          docker compose run --rm tests composer ci
      - name: Push image to ECR
        if: matrix.run_push == 'true'
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
          docker tag $APP_IMAGE:latest $REPOSITORY:test
          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
          docker push $REPOSITORY:test
          docker pull quay.io/keboola/syrup-cli:latest
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/') && matrix.run_deploy == 'true'
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: ./deploy.sh
